# config/database.yml
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "jaccess") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_DEV", "app_jumpingaccess_com_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_TEST", "app_jumpingaccess_com_test") %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME_PROD", "app_jumpingaccess_com_production") %>
    username: <%= ENV.fetch("DATABASE_USERNAME") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD") %>
    host: <%= ENV.fetch("DATABASE_HOST") %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("DATABASE_NAME_PROD") %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("DATABASE_NAME_PROD") %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("DATABASE_NAME_PROD") %>_cable
    migrations_paths: db/cable_migrate